name: CoderCo secrets CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: checkout code
      uses: actions/checkout@v2

    
    - name: use secrets
      run: echo "The secret is ${{ secrets.MY_SECRET }}"